/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: b69e6f634c5c13e10b93d5bb83b0c592)
// Runtime types generated with workerd@1.20250416.0 2025-02-04 nodejs_compat,nodejs_compat_populate_process_env
declare namespace Cloudflare {
	interface Env {
		CACHE_CHAT: KVNamespace;
		GOOGLE_GENERATIVE_AI_API_KEY: string;
		GATEWAY_BASE_URL: string;
		POLICY_AUD: string;
		TEAM_DOMAIN: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
	}
}
